### PR TITLE
update for seabios-1.7.5

### PR DESCRIPTION
**Pull request by jamescassell**
src/acpi.c was moved to src/fw/acpi.c

### CODE REVIEW

**Comment by dfateyev** [comment]
Unfortunately, it doesn't work as expected. Guest machines cannot see a proper SLIC table on 1.7.5:
table_1 7 5

The last working version for me was 1.7.2.2:
table_1 7 2

**Comment by cyberpear** [comment]
It works for me on RHEL 7.1 Beta.

**Comment by dfateyev** [comment]
Well, I tested on Debian (Proxmox 3.3), kernel 2.6.32, Win7 64bit guests, qemu-kvm version:
QEMU emulator version 2.1.2, Copyright (c) 2003-2008 Fabrice Bellard
That's really strange that 1.7.2.2 works there out of box, and newer version cause problems.

**Comment by cyberpear** [comment]
My version: QEMU emulator version 1.5.3 (qemu-kvm-1.5.3-60.el7_0.11), Copyright (c) 2003-2008 Fabrice Bellard

That could be the issue; something might have changed in the newer qemu, though it is strange that 1.7.2.2 works if its a qemu problem.

**Comment by cyberpear** [comment]
I'll try it out on Fedora soon if I get a chance.

**Pull request merged**
